main: fr.dariusmtn.minetrain.Main
version: b0.1
name: MineTrain
author: Slaymd
commands:
  minetrain:
    description: MineTrain main command.
    aliases: [mt,mtn]
  minetrainconfig:
    description: MineTrain config command.
    aliases: [mtc,mtnc]
permissions:
  minetrain.use:
    description: Allows you to use MineTrain system
    default: true
  minetrain.admin.*:
    description: Gives access to all MineTrain admin commands
    default: false
    children:
      minetrain.admin.list: true
      minetrain.admin.create: true
      minetrain.admin.remove: true
      minetrain.admin.edit: true
  minetrain.admin.list:
    description: Allows you to show the list
    default: op
  minetrain.admin.edit:
    description: Allows you to edit a line or station
    default: op
  minetrain.admin.create:
    description: Allows you to create new lines or stations
    default: op
  minetrain.admin.remove:
    description: Allows you to remove a line or station
    default: op
  