#MineTrain Carts move/clean nearby entities and if true, why.
#It serve to prevents Minecarts to stop due to a fu**in Creeper on the tracks!
#WARNING: CAN PRODUCE LAGS.
nearby_entities_manager: true

#Modes: PUSH, KILL_ALL, KILL_NOPLAYER
nearby_entities_manager_mode: PUSH

#Configurable messages
messages:
  change_for: "§e. Change for:§7 "
  next_stop: "§eNext Stop:§b %nextstop%"
  terminus: '§cTerminus.'

#Configurable title messages
titles:
  next_stop: "%newline%§eNext stop:§b %nextstop%"
  station: "§bStation%newline%§e%station%"